"""P0: sequences, which logical replication does not carry at all.

Every sequence advance on the source is invisible to replication.  If the
target's sequences are behind at cutover, the first insert hands out a value
that already exists — a duplicate-key outage minutes after go-live, in the
one window where rolling back is hardest.

So these tests care about one asymmetric property: the target may be ahead,
must never be behind.  They cover the forms a real schema mixes (serial,
bigserial, identity by default, identity always, standalone, cached) and the
conditions that make a naive implementation drift (inserts during the copy,
a cache block burned on the source, a sequence that only exists on one side).
"""

from __future__ import annotations

import asyncio

import pytest

from pg_emigrant.bootstrap import bootstrap
from pg_emigrant.db import connect
from pg_emigrant.sequence_sync import get_sequence_status, sync_sequences_once
from tests.helpers.replication import wait_for_catchup
from tests.helpers.verify import sequence_values

pytestmark = [pytest.mark.integration, pytest.mark.slow]

SCHEMAS = ["app", "reporting"]


async def _assert_target_not_behind(cfg, dbname):
    async with connect(cfg.source, dbname) as src, connect(cfg.target, dbname) as tgt:
        src_seq = await sequence_values(src, SCHEMAS)
        tgt_seq = await sequence_values(tgt, SCHEMAS)
    missing = sorted(set(src_seq) - set(tgt_seq))
    assert not missing, f"sequence(s) never created on the target: {missing}"
    behind = {k: (v, tgt_seq[k]) for k, v in src_seq.items() if tgt_seq[k] < v}
    assert not behind, (
        "target sequence(s) behind the source — the first insert after cutover "
        f"would collide with an existing row: {behind}"
    )
    return src_seq, tgt_seq


async def test_every_sequence_form_is_synchronised(cfg, source_db):
    """serial, bigserial, identity (by default and always), and standalone."""
    await bootstrap(cfg, database=source_db)
    src_seq, tgt_seq = await _assert_target_not_behind(cfg, source_db)

    for name in (
        "app.orders_id_seq",            # serial
        "app.documents_id_seq",         # bigserial
        "app.customers_id_seq",         # GENERATED BY DEFAULT AS IDENTITY
        "app.strict_identity_id_seq",   # GENERATED ALWAYS AS IDENTITY
        "app.ticket_seq",               # standalone, owned by nothing
        "app.cached_seq",               # CACHE 50
    ):
        assert name in tgt_seq, f"{name} was not created on the target"
        assert tgt_seq[name] >= src_seq[name], name


async def test_inserts_after_cutover_do_not_collide(cfg, source_db):
    """The property that actually matters, exercised end to end."""
    await bootstrap(cfg, database=source_db)
    await wait_for_catchup(cfg, source_db)
    await sync_sequences_once(cfg, source_db)

    async with connect(cfg.target, source_db) as tgt:
        # Stop applying changes first, the way a real cutover does.
        from pg_emigrant.replication import disable_subscription

        await disable_subscription(cfg, source_db)
        for _ in range(20):
            new_id = await tgt.fetchval(
                "INSERT INTO app.customers (email, display_name)"
                " VALUES ('cut' || gen_random_uuid() || '@example.com', 'post-cutover')"
                " RETURNING id"
            )
        assert new_id is not None
        # And on the identity-always table, whose sequence is created by the
        # table itself rather than pre-created by the schema sync.
        await tgt.fetchval(
            "INSERT INTO app.strict_identity (note) VALUES ('post-cutover') RETURNING id"
        )


async def test_a_cached_sequence_does_not_leave_the_target_behind(cfg, source_db):
    """CACHE makes last_value jump in blocks; the sync must respect that.

    Reading a cached sequence's ``last_value`` reports the end of the block
    the source reserved, not the last value handed out — so a target set to
    anything less than that can still collide.
    """
    await bootstrap(cfg, database=source_db)

    async with connect(cfg.source, source_db) as src:
        for _ in range(30):
            await src.fetchval("SELECT nextval('app.cached_seq')")

    await sync_sequences_once(cfg, source_db)
    await _assert_target_not_behind(cfg, source_db)


async def test_sequences_advanced_during_the_copy_are_caught_up(cfg, source_db):
    """A sequence that moves while data is being copied must not be missed."""
    from tests.helpers.workload import ConcurrentWriter

    async with ConcurrentWriter(cfg.source, source_db):
        await bootstrap(cfg, database=source_db)

    await wait_for_catchup(cfg, source_db)
    await sync_sequences_once(cfg, source_db)
    await _assert_target_not_behind(cfg, source_db)


async def test_the_margin_option_only_moves_sequences_forward(cfg, source_db):
    """--margin buys headroom for the gap between reading and stopping writes."""
    await bootstrap(cfg, database=source_db)

    async with connect(cfg.source, source_db) as src:
        before = await src.fetchval("SELECT last_value FROM app.ticket_seq")
        await src.fetchval("SELECT nextval('app.ticket_seq')")

    await sync_sequences_once(cfg, source_db, margin=1000)

    async with connect(cfg.target, source_db) as tgt:
        after = await tgt.fetchval("SELECT last_value FROM app.ticket_seq")
    assert after >= before + 1000, (
        f"the margin was not applied: target at {after}, source was at {before}"
    )


async def test_a_sequence_missing_on_the_target_is_reported_not_skipped(cfg, source_db):
    """Silently skipping it is a duplicate-key outage waiting for cutover."""
    await bootstrap(cfg, database=source_db)

    async with connect(cfg.target, source_db) as tgt:
        await tgt.execute("DROP SEQUENCE app.ticket_seq")

    report = await sync_sequences_once(cfg, source_db)
    entry = next((r for r in report if r["sequence"] == "ticket_seq"), None)
    assert entry is not None, (
        "a sequence that exists on the source but not on the target did not "
        "appear in the sync report at all"
    )
    assert entry["status"] == "missing_on_target"

    status = await get_sequence_status(cfg, source_db)
    assert any(
        r["sequence"] == "ticket_seq" and r["status"] == "missing_on_target"
        for r in status
    )


async def test_target_ahead_is_left_alone(cfg, source_db):
    """Sequences move forward only — never rewound to match the source."""
    await bootstrap(cfg, database=source_db)

    async with connect(cfg.target, source_db) as tgt:
        await tgt.execute("SELECT setval('app.ticket_seq', 999999)")

    await sync_sequences_once(cfg, source_db)

    async with connect(cfg.target, source_db) as tgt:
        assert await tgt.fetchval("SELECT last_value FROM app.ticket_seq") == 999999, (
            "the sync rewound a target sequence, which would re-issue used values"
        )


async def test_concurrent_inserts_during_sequence_sync(cfg, source_db):
    """The sync running against a moving source must still leave it not-behind."""
    from tests.helpers.workload import ConcurrentWriter

    await bootstrap(cfg, database=source_db)

    async with ConcurrentWriter(cfg.source, source_db, delay=0.001):
        for _ in range(5):
            await sync_sequences_once(cfg, source_db)
            await asyncio.sleep(0.05)

    await wait_for_catchup(cfg, source_db)
    await sync_sequences_once(cfg, source_db)
    await _assert_target_not_behind(cfg, source_db)
