-- Representative migration fixture.
--
-- One schema exercising the object kinds a real production database mixes
-- together, chosen so that every migration phase has something to get wrong:
-- types created before tables, sequences owned and standalone, constraints
-- validated post-copy, functions referenced by both defaults and triggers,
-- views layered on views, privileges granted to a non-owner role.
--
-- Deliberately portable across PostgreSQL 14-18: no syntax newer than 14 is
-- used, so the same fixture pins behaviour across the whole support matrix.

CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS reporting;

-- ── Roles referenced by ownership/privilege tests ────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_owner') THEN
        CREATE ROLE app_owner NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_reader') THEN
        CREATE ROLE app_reader NOLOGIN;
    END IF;
END $$;

-- ── Types ────────────────────────────────────────────────────────────────────
CREATE TYPE app.order_state AS ENUM ('draft', 'placed', 'shipped', 'cancelled');
CREATE DOMAIN app.email AS text CHECK (VALUE ~ '^[^@]+@[^@]+$');
CREATE TYPE app.address AS (street text, city text, zip text);

-- ── Sequences ────────────────────────────────────────────────────────────────
-- Standalone, not owned by any column: only the sequence-sync path keeps it
-- current, so a regression there is visible here and nowhere else.
CREATE SEQUENCE app.ticket_seq START 500 INCREMENT 7;
-- Cached sequence: nextval() burns a whole cache block per backend, so the
-- source's last_value jumps in steps of 50 rather than 1.
CREATE SEQUENCE app.cached_seq START 1 CACHE 50;

-- ── Tables ───────────────────────────────────────────────────────────────────
CREATE TABLE app.customers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        app.email NOT NULL UNIQUE,
    display_name text NOT NULL,
    home         app.address,
    tags         text[] DEFAULT '{}',
    profile      jsonb NOT NULL DEFAULT '{}'::jsonb,
    avatar       bytea,
    balance      numeric(18, 4) NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT balance_not_negative CHECK (balance >= 0)
);

-- SERIAL (not identity): a distinct sequence-ownership shape from customers.
CREATE TABLE app.orders (
    id          serial PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES app.customers(id) ON DELETE CASCADE,
    state       app.order_state NOT NULL DEFAULT 'draft',
    total_cents bigint NOT NULL DEFAULT 0,
    note        text,
    placed_at   timestamptz
);

-- Composite primary key + generated column + BIGSERIAL.
CREATE TABLE app.order_lines (
    order_id   integer NOT NULL REFERENCES app.orders(id) ON DELETE CASCADE,
    line_no    integer NOT NULL,
    sku        text NOT NULL,
    qty        integer NOT NULL CHECK (qty > 0),
    unit_cents bigint NOT NULL,
    total_cents bigint GENERATED ALWAYS AS (qty * unit_cents) STORED,
    PRIMARY KEY (order_id, line_no)
);

-- No primary key at all: forces REPLICA IDENTITY FULL handling.
CREATE TABLE app.audit_log (
    at      timestamptz NOT NULL DEFAULT now(),
    actor   text,
    action  text NOT NULL,
    payload jsonb
);

-- TOAST-heavy: wide text/bytea values stored out of line.
CREATE TABLE app.documents (
    id      bigserial PRIMARY KEY,
    title   text NOT NULL,
    body    text NOT NULL,
    blob    bytea
);

-- GENERATED ALWAYS AS IDENTITY: COPY must still be able to load explicit values.
CREATE TABLE app.strict_identity (
    id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    note text
);

-- Declarative partitioning: rows live in the leaves, never the parent.
CREATE TABLE app.events (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred date NOT NULL,
    kind     text NOT NULL,
    PRIMARY KEY (id, occurred)
) PARTITION BY RANGE (occurred);
CREATE TABLE app.events_2024 PARTITION OF app.events
    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
CREATE TABLE app.events_2025 PARTITION OF app.events
    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

-- Adversarial text: the characters that break a badly-quoted CSV COPY.
CREATE TABLE app.nasty_strings (
    id   integer PRIMARY KEY,
    val  text,
    note text
);

CREATE TABLE reporting.daily_totals (
    day         date PRIMARY KEY,
    order_count integer NOT NULL DEFAULT 0,
    cents       bigint NOT NULL DEFAULT 0
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX orders_customer_idx ON app.orders (customer_id);
CREATE INDEX orders_open_idx ON app.orders (placed_at) WHERE state <> 'cancelled';
CREATE UNIQUE INDEX customers_lower_email_idx ON app.customers (lower(email::text));
CREATE INDEX documents_title_idx ON app.documents USING btree (title text_pattern_ops);
CREATE INDEX customers_profile_idx ON app.customers USING gin (profile);

-- ── Functions / procedures ───────────────────────────────────────────────────
CREATE FUNCTION app.order_total(p_order_id integer) RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(sum(total_cents), 0)::bigint
    FROM app.order_lines WHERE order_id = p_order_id;
$$;

CREATE FUNCTION app.touch_order_total() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE app.orders SET total_cents = app.order_total(NEW.order_id)
    WHERE id = NEW.order_id;
    RETURN NEW;
END $$;

CREATE PROCEDURE app.recalc_daily(p_day date)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO reporting.daily_totals (day, order_count, cents)
    SELECT p_day, count(*), COALESCE(sum(total_cents), 0) FROM app.orders
    ON CONFLICT (day) DO UPDATE
        SET order_count = EXCLUDED.order_count, cents = EXCLUDED.cents;
END $$;

-- ── Triggers ─────────────────────────────────────────────────────────────────
CREATE TRIGGER order_lines_total
    AFTER INSERT OR UPDATE ON app.order_lines
    FOR EACH ROW EXECUTE FUNCTION app.touch_order_total();

-- ── Views ────────────────────────────────────────────────────────────────────
CREATE VIEW app.active_orders AS
    SELECT o.id, o.customer_id, c.display_name, o.state, o.total_cents
    FROM app.orders o JOIN app.customers c ON c.id = o.customer_id
    WHERE o.state <> 'cancelled';

CREATE VIEW reporting.customer_summary AS
    SELECT c.id, c.display_name, count(o.id) AS orders
    FROM app.customers c LEFT JOIN app.active_orders o ON o.customer_id = c.id
    GROUP BY c.id, c.display_name;

CREATE MATERIALIZED VIEW reporting.order_volume AS
    SELECT state, count(*) AS n FROM app.orders GROUP BY state;

-- ── Row-level security ───────────────────────────────────────────────────────
ALTER TABLE app.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_read_all ON app.audit_log FOR SELECT USING (true);

-- ── Ownership & privileges ───────────────────────────────────────────────────
ALTER SCHEMA app OWNER TO app_owner;
ALTER TABLE app.customers OWNER TO app_owner;
ALTER TABLE app.orders OWNER TO app_owner;
GRANT USAGE ON SCHEMA app TO app_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO app_reader;
GRANT SELECT, INSERT ON app.audit_log TO app_reader;
GRANT USAGE ON SEQUENCE app.ticket_seq TO app_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT ON TABLES TO app_reader;

-- ── Per-database settings ────────────────────────────────────────────────────
-- Carried by nothing except sync_db_settings; a miss only shows up after
-- cutover as a runtime search_path surprise.
ALTER DATABASE :"dbname" SET statement_timeout = '31s';
